// Configuración global — tablas de lookup REDCap
const CONFIG = {
    campos: {
        fecha_inicio: 'fecha_de_inicio',
        nombre_actividad: 'nombre_de_la_actividad',
        tipo_actividad: 'tipo_de_actividad',
        tematica: 'qu_tem_tica_s_aborda_la_ac',
        programa: 'en_qu_estrategia_plan_inte',
        participantes: 'asist_total',
        hombres: 'asist_hombres',
        mujeres: 'asist_mujeres',
        horas: 'n_mero_de_horas',
        sesiones: 'n_mero_de_sesiones',
        profesional: 'apellidos_y_nombre',
        distrito: 'distrito0',
        unidad_granada: 'unidad_asistencial',
        unidad_metro: 'unidad_asistencial_2',
        unidad_nombre: 'unidad_nombre_referencia'
    },
    tipos_actividad: {
        '0': 'Charla',
        '1': 'Comisión/grupo trabajo',
        '2': 'Control Alerta Salud Pública',
        '3': 'Entrevista/Reunión',
        '4': 'Intervención en medios',
        '5': 'Intervención grupal: personas cuidadoras',
        '6': 'Intervención grupal: dolor',
        '7': 'Intervención grupal: educación diabetológica',
        '8': 'Intervención grupal: EPOC/asma',
        '9': 'Intervención grupal: rehabilitación cardiaca',
        '10': 'Intervención grupal: rehabilitación respiratoria',
        '11': 'Educación maternal',
        '12': 'GRAFA',
        '13': 'GRUSE',
        '14': 'IAHS',
        '15': 'PIOBIN',
        '16': 'PITA',
        '17': 'PSIA',
        '18': 'Mapeo activos',
        '19': 'Mesa informativa/stand',
        '20': 'Ponencia/comunicación',
        '21': 'Sesión clínica',
        '22': 'Sesión formativa',
        '23': 'Taller',
        '24': 'Otros'
    },
    tematicas: {
        '1': 'Actividad física',
        '2': 'Activos para la salud',
        '3': 'Alimentación saludable',
        '4': 'Bienestar emocional',
        '5': 'Conducta suicida',
        '6': 'Consumo de alcohol',
        '7': 'Consumo de tabaco',
        '8': 'Dolor',
        '9': 'Enfermedades transmisibles',
        '10': 'Envejecimiento saludable',
        '11': 'Higiene de manos',
        '12': 'Higiene postural',
        '13': 'Incontinencia urinaria',
        '14': 'Infecciones relacionadas con atención sanitaria',
        '15': 'Lactancia materna',
        '16': 'Manejo terapéutico enfermedad',
        '17': 'Menopausia',
        '18': 'Otras adicciones',
        '19': 'Otras formas de fumar',
        '20': 'Parentalidad positiva',
        '21': 'Prevención accidentabilidad',
        '22': 'Primeros auxilios',
        '23': 'Salud bucodental',
        '24': 'Sexualidad',
        '25': 'Uso adecuado medicamento',
        '26': 'Uso adecuado TRICs',
        '27': 'Vacunas',
        '28': 'Violencia de género',
        '29': 'Voluntades vitales y muerte digna',
        '30': 'Otra'
    },
    programas: {
        '1': 'Centros Comprometidos Violencia Género',
        '2': 'En Buena Edad',
        '3': 'Escuela de Pacientes',
        '4': 'Estrategia AVISTA',
        '5': 'Estrategia de Cuidados',
        '6': 'Estrategia Seguridad Paciente',
        '7': 'Estrategia Vida Saludable (EVSA)',
        '8': 'Forma joven otros entornos',
        '9': 'GRAFA',
        '10': 'GRUSE',
        '11': 'Jornadas/Semanas de la salud',
        '12': 'Mapa Activos salud',
        '13': 'PAITSIDA',
        '14': 'PAPEF',
        '15': 'Plan Humanización',
        '16': 'PIOBIN',
        '17': 'PITA',
        '18': 'Plan participación ciudadana',
        '19': 'PSIA',
        '20': 'Prevención conducta suicida',
        '21': 'Por 1 Millón pasos',
        '22': 'PromoSalud ámbito educativo',
        '23': 'PSLT',
        '24': 'RELAS',
        '25': 'Otros'
    },
    unidades_granada: {
        '0': 'Albayzín',
        '1': 'Almanjáyar',
        '2': 'Cartuja',
        '3': 'Casería de Montijo',
        '4': 'Caleta',
        '5': 'Chana',
        '6': 'Gran Capitán',
        '7': 'Flores-Fígares',
        '8': 'Fortuny/Velluti',
        '9': 'Zaidín Centro-Este',
        '10': 'Zaidín Sur',
        '11': 'Gógora',
        '12': 'Realejo',
        '13': 'Bola de Oro',
        '14': 'Doctores'
    },
    unidades_metro: {
        '0': 'Albolote',
        '1': 'Alfacar',
        '2': 'Alhama de Granada',
        '3': 'Armilla',
        '4': 'Atarfe',
        '5': 'Cenes de la Vega',
        '6': 'Churriana de la Vega',
        '7': 'Huétor-Tájar',
        '8': 'Huétor-Vega',
        '9': 'Íllora',
        '10': 'Iznalloz',
        '11': 'La Zubia',
        '12': 'Las Gabias',
        '13': 'Loja',
        '14': 'Maracena',
        '15': 'Montefrío',
        '16': 'Ogíjares',
        '17': 'Peligros',
        '18': 'Pinos Puente',
        '19': 'Santa Fe',
        '20': 'Valle de Lecrín'
    },
    colores: {
        primario: '#1976d2',
        secundario: '#388e3c',
        acento1: '#f57c00',
        acento2: '#d32f2f',
        acento3: '#9c27b0',
        acento4: '#0288d1',
        paleta: ['#1976d2', '#388e3c', '#f57c00', '#d32f2f', '#9c27b0', '#0288d1', '#00796b', '#c2185b']
    }
};

export { CONFIG };
